name = master_flame
description = The Most Powerful Tool on Luanti is there! Inspired by Alien Tools, Alien Flame item!
author = abelhona
depends = default, moreores, alien_tools, alien_material, tools_obsidian, wielded_light
license = MIT
media_license = CC-BY-SA-4.0
